[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test/foundry"
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

[profile.ci]
verbosity = 2
fuzz = { runs = 1000 }

[rpc_endpoints]
base = "${BASE_RPC}"
baseSepolia = "${BASE_SEPOLIA_RPC}"

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
